[package]
name = "smumerix-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
approx = "0.5.1"
nalgebra = "0.32.1"
rand = "0.8.5"
